name: Firebase deploy

on:
  push:
    branches:
      - master

jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    steps:
    #checkout master brunch
    - uses: actions/checkout@v2
      with:
        repository: 'master'
    - name: Install Dependencies
      run: yarn
    - name: Build
      run: yarn generate:prd
