name: Firebase deploy

on:
  push:
    branches:
      - master

jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    steps:
    #checkout master brunch
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.master }}
#     - name: setup Node
#       uses: actions/setup-node@v1
#       with: 
#         node-version: 10.x
#         registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: yarn install
    - name: Generate
      run: yarn generate:prd
