name: Firebase deploy

on:
  push:
    branches:
      - develop

    paths-ignore:
      - '.github/**/*.md'
      - '.idea/**'
      - '.vscode/**'
      - 'intellij-config.js'
      - 'jsconfig.json'
      - 'README.md'

jobs:
  build_staging_files:
    name: Build staging files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: develop

      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: deploy-to-staging-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            deploy-to-staging-yarn-
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build:stg

# on:
#   push:
#     branches:
#       - master

# jobs:
#   firebase_deploy:
#     runs-on: ubuntu-latest
#     steps:
#     #checkout master brunch
#     - uses: actions/checkout@v2
#       with:
#         repository: ${{ github.master }}
#     - name: Setup Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: "12.5"
#     - name: Install Dependencies
#       run: yarn install
#     - name: Generate
#       run: yarn generate:prd
